name: Auto Tap Script CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Termux environment
      run: |
        sudo apt update
        sudo apt install -y termux
        
    - name: Run auto-tap script
      run: |
        chmod +x autotap.sh
        ./autotap.sh
